# Training Params
n_epochs: 10
batch_size: 128
lr: 0.001
l2_reg: 0.005
weight_penalty_factor: 0.02

# Model Params
#n_channels: [5, 16, 32]
#kernel_sizes: [3, 3]
n_channels: []
kernel_sizes: []
fc_units: [32, 32, 16]



