# Training Params
n_epochs: 50
batch_size: 512 # Seems to work well
#batch_size: 1024
lr: 0.001
#l2_reg: 0.005 # Seems to work well
#l2_reg: 0.001 # Also seems to work well
l2_reg: 0.0025
weight_penalty_factor: 0.02

# Model Params
#n_channels: [5, 16, 32]
#kernel_sizes: [3, 3]
#n_channels: []
#kernel_sizes: []
fc_units: [32, 32, 16] # Seems to work well
#fc_units: [32, 64, 64]



