# Training Params
batch_size: 64
#batch_size: 64
#lr: 0.001
lr: [0.001, 0.0005, 0.0001]
lr_epochs: [33, 66]
l2_reg: 0.001
#l2_reg: 0.0005

misfit_fn: "mse"
#misfit_fn: "mae"


# Model Params
# Independent Model

#ind_fc_units: [16, 16, 16]
ind_fc_units: [16, 16]
#ind_fc_units: [64, 128, 64]

use_combined_model: False
#use_combined_model: True
comb_fc_units: [32, 16]

# IM features
im_sim_site_obs: False
#im_sim_site_obs: True
im_sim_site_int: False
#im_sim_site_int: True
im_obs_site_obs: False
#im_obs_site_obs: True

#res_site_obs: False
res_site_obs: True
#res_sim_site_obs_sim_site_int: False
res_sim_site_obs_sim_site_int: True
#res_obs_site_obs_sim_site_int: False
res_obs_site_obs_sim_site_int: True




