# Training Params
n_epochs: 100
batch_size: 1024
lr: 0.001
l2_reg: 0.001
weight_penalty_factor: 0.02

# Model Params
n_channels: [1, 64, 128, 256, 512]
kernel_sizes: [3, 3, 3, 3]
fc_units: [512, 256, 128, 64]



