# Hyperparameters
batch_size: [256, 512, 1024, 2048]

n_gcn_layers:
  min: 1
  max: 3
n_obs_node_channels: [16, 32, 64]
n_int_node_channels:
  min: 2
  max: 8
  step: 2
n_edge_channels:
  min: 2
  max: 12
  step: 2
gcn_act_fn: ["relu", "leaky_relu"]

n_att_heads:
  min: 2
  max: 10
  step: 2
att_n_units:
  min: 2
  max: 12
  step: 2
att_act_fn: ["relu", "leaky_relu"]

fc_n_units: [8, 16, 32, 64]
fc_act_fn: ["relu", "leaky_relu"]

# batch_norm: [True, False]

l2_reg: [0.0001, 0.001, 0.01]

dropout_rate: [0.0, 0.1, 0.2, 0.3]


