### All paths specified are relative to the environment variable $wdata

# General settings
seed: 42

# Input data settings
#rel_obs_data_ffp: gm_datasets/nz_gmdb/v3.4/Tables/ground_motion_im_table_rotd50_flat.csv
rel_obs_data_ffp: gm_datasets/nz_gmdb/v4.0/Tables/ground_motion_im_table_rotd50_flat.csv
max_dist: 20
max_n_obs_sites: 10

# Features
graph_feature_keys:
  edge:
    - "dist"
    - "angular_dist"
  site_int:
    - "vs30_site_int"
    - "z1p0_site_int"
    - "z2p5_site_int"
    - "tsite_site_int"
    - "rrup_site_int"
    - "mag"
  site_obs:
    - "vs30_site_obs"
    - "z1p0_site_obs"
    - "z2p5_site_obs"
    - "tsite_site_obs"
    - "rrup_site_obs"

# Model settings
pred_std: True
scale_IMs: True

# Hyperparameters
n_epochs: 100
batch_size: 1024
fc_n_units: 32
n_int_node_channels: [62]

# Output settings
rel_results_dir: sim_ranking/results/gnn