### All paths specified are relative to the environment variable $wdata

# General settings
seed: 42

# Input data settings
rel_obs_data_ffp: gm_datasets/nz_gmdb/v3.0/Tables/ground_motion_im_table_rotd50_flat.csv
max_dist: 25
n_val_events: 750
n_val_sites: null
rel_val_sites_ffp: sim_ranking/configs/0827_0831_val_int_sites.npy
val_events: ["3468575"]
test_events: ["2016p118944", "3528839", "3525264"]
#test_events: ["2016p118944", "3468575", "3528839", "3525264"]


# Model settings
pred_std: True

# Hyperparameters
n_epochs: 100
batch_size: 1024
fc_n_units: 32
n_int_node_channels: [62]

# Output settings
rel_results_dir: sim_ranking/results/gnn